// Command gen-widths emits internal/textwidth/tables.go from the Unicode
// character database.
//
// It writes tables.go into the working directory; go:generate runs it from
// internal/textwidth.
//
// Usage: go run ../../tools/gen-widths EastAsianWidth.txt emoji-data.txt
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// outPath is relative to the working directory.
const outPath = "tables.go"

type rng [2]rune

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: gen-widths EastAsianWidth.txt emoji-data.txt")
		os.Exit(2)
	}

	unicodeVersion, err := agreedVersion(os.Args[1], os.Args[2])
	if err != nil {
		fatal(err)
	}

	eaw, err := parse(os.Args[1])
	if err != nil {
		fatal(err)
	}
	emoji, err := parse(os.Args[2])
	if err != nil {
		fatal(err)
	}

	wide := append(eaw["W"], eaw["F"]...)
	wide = append(wide, emoji["Emoji_Presentation"]...)
	ambiguous := eaw["A"]

	// Zero-width codepoints outside the Mn, Me and Cf categories, which are
	// consulted at lookup time.
	zero := []rng{
		{0x1160, 0x11FF}, // Hangul jungseong and jongseong: EAW=N, but they
		// conjoin with a leading jamo, and wcwidth and terminals give the
		// syllable the leading jamo's two columns
		{0x200B, 0x200B}, // zero width space
		{0x200D, 0x200D}, // zero width joiner
		{0xFE00, 0xFE0F}, // variation selectors
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tools/gen-widths; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package textwidth\n\n")
	fmt.Fprintf(&b, "// UnicodeVersion is the UCD release these tables come from.\n")
	fmt.Fprintf(&b, "const UnicodeVersion = %q\n", unicodeVersion)
	emit(&b, "wide", "East Asian Wide and Fullwidth, plus Emoji_Presentation.", merge(wide))
	emit(&b, "ambiguous", "East Asian Ambiguous.", merge(ambiguous))
	emit(&b, "zero", "Zero-width codepoints outside categories Mn and Me.", merge(zero))

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
}

// versionPatterns match the two ways a UCD file states its release: the
// "# EastAsianWidth-16.0.0.txt" name line, and the "# Used with Emoji Version
// 16.0" line that emoji-data.txt carries instead.
var versionPatterns = []*regexp.Regexp{
	regexp.MustCompile(`^#\s*\S+-([0-9]+(?:\.[0-9]+)+)\.txt`),
	regexp.MustCompile(`^#.*\bVersion\s+([0-9]+(?:\.[0-9]+)+)`),
}

// agreedVersion reads both files' declared release and returns it. The two
// must name the same major and minor version.
func agreedVersion(a, b string) (string, error) {
	va, err := fileVersion(a)
	if err != nil {
		return "", err
	}
	vb, err := fileVersion(b)
	if err != nil {
		return "", err
	}
	if release(va) != release(vb) {
		return "", fmt.Errorf("%s is Unicode %s but %s is Unicode %s", a, va, b, vb)
	}
	if strings.Count(va, ".") >= strings.Count(vb, ".") {
		return pad(va), nil
	}
	return pad(vb), nil
}

// fileVersion reads the release a UCD file declares in its header comment.
func fileVersion(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if !strings.HasPrefix(line, "#") {
			break
		}
		for _, re := range versionPatterns {
			if m := re.FindStringSubmatch(line); m != nil {
				return m[1], nil
			}
		}
	}
	if err := sc.Err(); err != nil {
		return "", err
	}
	return "", fmt.Errorf("%s: no Unicode version in the header", path)
}

// release is the major and minor of a version.
func release(v string) string {
	parts := strings.SplitN(v, ".", 3)
	if len(parts) < 2 {
		return v
	}
	return parts[0] + "." + parts[1]
}

// pad extends a two-part version to three.
func pad(v string) string {
	if strings.Count(v, ".") == 1 {
		return v + ".0"
	}
	return v
}

// parse reads a UCD data file and groups its ranges by property value.
func parse(path string) (map[string][]rng, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	out := make(map[string][]rng)
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 2 {
			continue
		}
		codes := strings.TrimSpace(fields[0])
		prop := strings.TrimSpace(fields[1])
		if codes == "" || prop == "" {
			continue
		}
		lo, hi, err := codepoints(codes)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		out[prop] = append(out[prop], rng{lo, hi})
	}
	return out, sc.Err()
}

// codepoints parses "1F600" or "1F600..1F64F".
func codepoints(s string) (rune, rune, error) {
	lo, hi, found := strings.Cut(s, "..")
	if !found {
		hi = lo
	}
	l, err := strconv.ParseUint(lo, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	h, err := strconv.ParseUint(hi, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	return rune(l), rune(h), nil
}

// merge sorts ranges and coalesces those that touch or overlap.
func merge(in []rng) []rng {
	if len(in) == 0 {
		return nil
	}
	sorted := make([]rng, len(in))
	copy(sorted, in)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i][0] != sorted[j][0] {
			return sorted[i][0] < sorted[j][0]
		}
		return sorted[i][1] < sorted[j][1]
	})
	out := []rng{sorted[0]}
	for _, r := range sorted[1:] {
		last := &out[len(out)-1]
		if r[0] <= last[1]+1 {
			if r[1] > last[1] {
				last[1] = r[1]
			}
			continue
		}
		out = append(out, r)
	}
	return out
}

func emit(b *strings.Builder, name, doc string, ranges []rng) {
	fmt.Fprintf(b, "\n// %s: %s\nvar %s = [][2]rune{\n", name, doc, name)
	for _, r := range ranges {
		fmt.Fprintf(b, "\t{0x%04X, 0x%04X},\n", r[0], r[1])
	}
	fmt.Fprintf(b, "}\n")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-widths:", err)
	os.Exit(1)
}
